import Head from 'next/head';
import Image from 'next/image';
import React, { useMemo, useState } from 'react';
import { Inter } from 'next/font/google';
import { useTranslation } from 'next-i18next';
import { useRouter } from 'next/router';
import { GoogleMap, useLoadScript, Marker } from "@react-google-maps/api";

import styles from '@/styles/Home.module.css';
import { useAuth } from '@/store/auth/useAuth';
import { useGetPosts, useLogin } from './service';
import { getAccessToken } from '@/store/auth';
import { ENV } from '@utils/env';


const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  const [loginStatus, setLoginStatus] = useState(getAccessToken() ? 'Logged in!' : 'Not log in!');
  const { onLogin } = useAuth();
  const {dataPosts, run: runGetPosts} = useGetPosts();

  const { isLoaded } = useLoadScript({
    googleMapsApiKey: ENV.GOOGLE_MAP_API_KEY,
  });
  const center = useMemo(() => ({ lat: 44, lng: -80 }), []);

  const { t } = useTranslation('home');
  const router = useRouter();
  const currentLang = router.locale;

  const onChangeLang = (lang: string) => () => {
    if (lang !== currentLang) {
      router.push(router.pathname, router.asPath, {
        locale: lang,
      });
    }
  };

  const onSubmitLogin = () => {
    requestLogin.run();
  };


  const requestLogin = useLogin({
    onSuccess: (res: any) => {
      if (res?.accessToken) {
        onLogin({
          token: res?.accessToken,
          refreshToken: res?.refreshToken,
        });
      setLoginStatus('Logged in!');
      }
    },
    onError(e) {
      setLoginStatus(e?.errors?.[0] || e?.message);
    },
  });

  const onGetPosts = () => {
    runGetPosts()
  }


  if (!isLoaded) return null;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div className={styles.languageContainer}>
            <div onClick={onChangeLang('vi')} className={styles.languageText}>Tiếng Việt</div>
            <div onClick={onChangeLang('en')} className={styles.languageText}>English</div>
          </div>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a 
            className={styles.card}
            onClick={onSubmitLogin}
          >
            <h2>
              {t('login')} <span>-&gt;</span>
            </h2>
            <p>
              {t('login_container_content')}
            </p>
          </a>

          <a
            className={styles.card}
            onClick={onGetPosts}
          >
            <h2>
              {t('get_posts')} <span>-&gt;</span>
            </h2>
            <p>
              {t('get_posts_container_content')}
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>

        <div className={styles.contentContainer}>
          <p>{loginStatus}</p>
          {dataPosts?.posts.map((item: any, index: number) => (
            <>
              Post {index}: {item.title}
              <br />
            </>
          ))}
        </div>

        <GoogleMap zoom={10} center={center} mapContainerClassName={styles.mapContainer}>
          <Marker position={center} />
        </GoogleMap>
      </main>
    </>
  );
};

export default Home;
